### ISSUE TITLE
Missing config files

### ISSUE THREAD

**Issue by iovcho** [angrycub/nomad_example_jobs#2]
Hello @angrycub  
I try to run this nomad job
https://github.com/angrycub/nomad_example_jobs/blob/master/httpd_site/httpd.nomad

But there have missing 
failed to download artifact "https://angrycub-hc.s3.amazonaws.com/public/templated-industrious.zip": bad response code: 404

Can you re-upload or can you upload it in github ? 
Best wishes.

**Comment by angrycub** [comment]
Thanks for the report! I've updated the sample to use a link to a site tarball served by Github as you suggested. I also updated it to use the new group level network stanza (which is the now correct way to do it in Nomad versions 0.12 and greater)
