### ISSUE TITLE
All plans need to  update to support nomad 1.0 onwards

### ISSUE THREAD

**Issue by thatsk** [angrycub/nomad_example_jobs#3]
Hello @angrycub , Most of plans are now deprecated i think we need to update that all the plans.

**Comment by angrycub** [comment]
Indeed.  Working in the in-progress branch to try to catch them up, but there's a lot of examples and a little of me. :D I think I'm about half way there.  I should probably just merge that work into main so it doesn't look totally abandoned.

Thanks for the nudge and for your interest in the repo!
